/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container': '#1f1f1f',
        'primary-fixed-dim': '#2fd9f4',
        'on-secondary-fixed': '#261900',
        'surface-container-low': '#1b1b1b',
        'on-tertiary-fixed-variant': '#3d4662',
        'primary-container': '#22d3ee',
        'secondary-fixed-dim': '#ecc06a',
        'error-container': '#93000a',
        'on-surface-variant': '#bbc9cd',
        'on-primary': '#00363e',
        'surface-container-lowest': '#0e0e0e',
        'tertiary-fixed': '#dbe1ff',
        'surface-tint': '#2fd9f4',
        surface: '#131313',
        'on-surface': '#e2e2e2',
        'on-background': '#e2e2e2',
        'on-tertiary-container': '#454e6b',
        'secondary-container': '#715200',
        'surface-container-high': '#2a2a2a',
        tertiary: '#d3dcff',
        'inverse-surface': '#e2e2e2',
        'on-secondary': '#402d00',
        background: '#131313',
        'outline-variant': '#3c494c',
        'tertiary-fixed-dim': '#bcc5e8',
        'surface-variant': '#353535',
        'on-error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#5d4200',
        'on-error': '#690005',
        'on-tertiary': '#262f4b',
        outline: '#859397',
        'on-tertiary-fixed': '#111a35',
        'on-primary-fixed-variant': '#004e5a',
        'on-primary-container': '#005763',
        error: '#ffb4ab',
        primary: '#8aebff',
        'surface-dim': '#131313',
        'surface-container-highest': '#353535',
        'secondary-fixed': '#ffdea3',
        secondary: '#ecc06a',
        'primary-fixed': '#a2eeff',
        'inverse-primary': '#006877',
        'tertiary-container': '#b7c0e2',
        'surface-bright': '#393939',
        'on-secondary-container': '#f3c770',
        'on-primary-fixed': '#001f25',
        'inverse-on-surface': '#303030',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        gutter: '24px',
        'margin-mobile': '16px',
        base: '8px',
        'margin-desktop': '40px',
      },
      fontFamily: {
        'headline-lg': ['Sora', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Sora', 'sans-serif'],
        'headline-md': ['Sora', 'sans-serif'],
        'headline-xl': ['Sora', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'label-sm': ['Geist', 'sans-serif'],
        headline: ['Sora', 'sans-serif'],
        display: ['Sora', 'sans-serif'],
        body: ['Hanken Grotesk', 'sans-serif'],
        label: ['Geist', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.8s ease-out forwards',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        orbit: 'orbit linear infinite',
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: 0, transform: 'translateY(20px)' },
          '100%': { opacity: 1, transform: 'translateY(0)' },
        },
        orbit: {
          '0%': { transform: 'translate(-50%, -50%) rotate(0deg)' },
          '100%': { transform: 'translate(-50%, -50%) rotate(360deg)' },
        },
      },
    },
  },
  plugins: [],
};
